version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing source npm dependencies..."
      - npm install
  build:
    commands:
      - echo "Build started."
      - npm run static-build # Command to build the Next.js app
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - out/**/*
  discard-paths: no
  base-directory: out